<a href="https://colab.research.google.com/github/CalebaR/MAT-421/blob/main/ModuleD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.1: Introduction**\
This chapter goes over many basics of linear algebra such as linear spaces, orthogonality, eigenvalues, eigenvectors, matrix decomposition and linear regression.

**1.2: Elements of Linear Algebra**

In [44]:
#vector/linear spaces can be represented a few ways in python

#lists
list1 = [1,2,3,"four",5.0]

#array
import array as arr
arr1 = arr.array('i',[1,2,3])

#tuple
tuple1 = 1,2,3,"four",5.0

import numpy as np

#there are also arrays from numpy
vec1 = np.array([[1,2,3]])
vec2 = np.array([[1,2],[3,4]])
print(vec1)
print(vec2)

#transposing vectors
print(vec1.T)

#vector norms in vector space. These are ways to measure the size of the vector
from numpy.linalg import norm

print(norm(vec1,1))
print(norm(vec1,2))
print(norm(vec1,np.inf))

vec3 = np.array([[0.1,0.2,0.3]])

#vector manipulation
print(vec1*10)
print(vec1+vec3)
print(vec1*vec3)

#dot product
print(np.dot(vec2,vec2))

#cross product
print(np.cross(vec2,vec2))

#orthogonality
vec4 = np.array([1,1])
vec5 = np.array([2,2])

theta = np.arccos(np.dot(vec4, vec5.T)/(norm(vec4)*norm(vec5)))
print(theta)

#linear combination
vec6 = np.array([[0, -2, 0]])
print(3*vec1+2*vec3-4*vec6)

#linear independence
v = [1,1,0]
w=[1,0,0]
u=[0,0,1] #these vectors are all linearly independent because none of vectors can be written as linear combinations of each other

#matrices can easily be made from the same np.array function
matrix = np.array([[1,2],[3,4]])
print(matrix)

#LU decomposition
u = np.array([[4, 3, -5],
              [0, -2.5, 2.5],
              [0, 0, 12]])
l = np.array([[1, 0, 0],
              [-0.5, 1, 0],
              [2, -0.8, 1]])

print('LU=', np.dot(l, u))

[[1 2 3]]
[[1 2]
 [3 4]]
[[1]
 [2]
 [3]]
3.0
3.7416573867739413
6.0
[[10 20 30]]
[[1.1 2.2 3.3]]
[[0.1 0.4 0.9]]
[[ 7 10]
 [15 22]]
[0 0]
2.1073424255447017e-08
[[ 3.2 14.4  9.6]]
[[1 2]
 [3 4]]
LU= [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


**1.3: Linear Regression**